### ISSUE TITLE
Body already closed

### ISSUE THREAD

**Issue by jakekeeys** [travisghansen/freenas-iscsi-provisioner#2]
https://github.com/travisghansen/freenas-iscsi-provisioner/blob/3efd032191337c7256aba9cfc43d6bb53b532d08/freenas/zvol.go#L75-L76

The sling http client wrapper used throughout the freenas client implementation will always close the http response body before returning to the caller

https://github.com/dghubble/sling/blob/22538d0bac4e8b6337114fccfdfeb6d1ad0ef2d2/sling.go#L383

the read call swallows the error and we end up logging an empty byte slice

I don't think there's much you can do other than refactor out sling as that response is vital for debugging those calls.

**Comment by travisghansen** [comment]
Wow didn't think anyone was using this!  I'll take a closer look and probably accept everything as I basically taught myself go over a weekend to make this so I'm sure there are some ugly things.

**Comment by jakekeeys** [comment]
Just a pet project for me,

I've closed the PR after realising one of the changes i had made was wrong (removing the zvol prefix when creating the extent) fully understand and sympathise with your comments regarding the api semantics which isn't helped by inconsistencies and gaps in the documentation :P 

I got the provisioning working but couldn't then mount the volumes due to kubernetes api changes. The `ISCSIPersistentVolumeSource` now requires you to pass an `InitiatorName` which didn't exist in the version of the kubernetes client used here. Rather than fighting with dependencies I've started writing and nearly finished an equivalent (https://github.com/jakekeeys/freenas-provisioner), once its done ill have another stab at brining yours in line with the current k8s client.

**Comment by travisghansen** [comment]
@jakekeeys ok, I hadn't forgotten about this, was getting close to review.  Big picture what I'd really like to do is use this as a playground for migrating the code base to use the `v2` FreeNAS api and ultimately convert it to be a CSI driver.

I'd probably do those in steps.  Use `v2` first and then retool it to be a CSI driver later.

**Comment by jakekeeys** [comment]
sounds like a plan, I've got everything up and running here now which should tide me over, happy to lend a hand and start looking at v2

**Comment by travisghansen** [comment]
Just to be clear you absolutely need block (iscsi) and file (nfs) won't do for your use-case?  The nfs provisioner is really more developed (and technically far less moving parts).  I've been using it in a couple of near-production clusters for over a year with few issues.

**Comment by jakekeeys** [comment]
For the most part NFS is fine and my default storageclass, I have a few applications like Plex that come bundled with SQLite and don't appreciate the NFS backing

**Comment by jakekeeys** [comment]
Just to add it would be nice to lean on the dataset creation for NFS too along with some of the authentication options which would steer me towards writing a more generic Freenas provisioner that implemented ISCSI and NFS storage classes

**Comment by travisghansen** [comment]
Ah yep.  Exactly why I wrote this was to handle those edge cases.

A unified provisioner is not a bad idea.  Makes the configuration a bit more convoluted but deployment and code may be easier to maintain.

The NetApp provisioner goes a step further and allows for a single storage class to be serviced by multiple appliances.  It's tries to find the appliance/pool with the least used storage and provisions there.  I don't recommend this route but just to show with some of these things you can add a lot of complexity real fast.

**Comment by travisghansen** [comment]
@jakekeeys as an FYI I'm revisiting this just enough to get it over the hill and get a release out with proper images built etc.  I'm currently planning a csi driver for zfs based systems but csi is a bit of a mess honestly so I'm working with the storage folks to make it...better.

**Comment by travisghansen** [comment]
@jakekeeys OK, I've completely gutted much of the project and put into good enough shape until csi get into a better state.  For your particular error there's a very crude attempt at pulling a response in so give it a whirl and see what you get...it works for me but for whatever error you're getting the structure of the json may be slightly different. I'll probably make it more generic when I get a chance..

In any case, the overall state of the project is *much* better than it was and to a state that I'm comfortable running it in a semi production environment now (staging lab used by ~30 people). I've ran through several tests spinning up 100 vols and tearing them all down several times now and it's worked flawlessly over each attempt.

Try it out and let me know how it goes..
