### ISSUE TITLE
freenas-iscsi-provisioner crash looping

### ISSUE THREAD

**Issue by mattmattox** [travisghansen/freenas-iscsi-provisioner#4]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Rancher: v2.3.1
- Docker: 17.3.2
- Kubernetes: v1.14.6
- FreeNAS: FreeNAS-11.1-U7

**Error**
I1026 02:06:51.926093       1 extent.go:99] found Extent name: pvc-d1ab8b20-f794-11e9-986f-005056a21ea8 - {ID:1 AvailThreshold:0 Blocksize:512 Comment:default/freenas-test-iscsi-pvc Filesize:0 InsecureTpc:true Legacy:false Naa:0x6589cfc0000005bdb190bf0a3b2053c2 Name:pvc-d1ab8b20-f794-11e9-986f-005056a21ea8 Path:/dev/zvol/DiskPool0/k8s/pvc-d1ab8b20-f794-11e9-986f-005056a21ea8 Disk:zvol/DiskPool0/k8s/pvc-d1ab8b20-f794-11e9-986f-005056a21ea8 Pblocksize:true Ro:false Rpm:SSD Serial:90e2ba81b69800 Type:ZVOL Xen:false}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfb7109]

goroutine 238 [running]:
github.com/travisghansen/freenas-iscsi-provisioner/provisioner.(*freenasProvisioner).Provision(0xc0003a82c0, 0xc0004d82f8, 0x6, 0xc0000141e0, 0x28, 0x0, 0x0, 0x0, 0xc0000ac340, 0xc0004d1e00, ...)
        /home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/provisioner/provisioner.go:570 +0x1b09
github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).provisionClaimOperation(0xc0000fc380, 0xc0000ac340, 0x1f44060, 0xc0005094b0)
        /home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:1066 +0xdf2
github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).lockProvisionClaimOperation.func1(0xc0001d4360)
        /home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:935 +0x76
created by github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection.(*LeaderElector).Run
        /home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection/leaderelection.go:129 +0xad

**Comment by travisghansen** [comment]
Interesting. Few questions:

- Does the corresponding/correct `Associated Target` exist in FreeNAS?
- Do you have other volumes that have provisioned successfully or is this the first attempt?
- How many (roughly) `Associated Targets` exist on this server?
- Can you share the logging from the pod leading up to the failure?

**Comment by travisghansen** [comment]
Figure this one out?
