### ISSUE TITLE
zvol volume not deleting

### ISSUE THREAD

**Issue by UMB8998** [travisghansen/freenas-iscsi-provisioner#9]
Amazing program, thank you.
Are the zvol and LUN supposed to get deleted after deleting the PVC?

**Comment by travisghansen** [comment]
Yes if the policy is set to `Delete` on the storage class.

**Comment by UMB8998** [comment]
My mistake the LUN, was connected to other machine that's why it didn't got deleted, on other test, the system work perfect, thank you

**Comment by travisghansen** [comment]
@UMB8998 if you're just getting started I would suggest the newer version of this project: https://github.com/democratic-csi/charts

This project (as well as all other non-csi drivers) are basically in maintenance mode. The other project has far more advanced features such as resizing and snapshot support etc.

**Comment by UMB8998** [comment]
Thank you very much, I took a look at it, but I can't find the configurable parameters of the chart. Should I be using a mix between the "freenas-iscsi.yaml" template and the "values.yaml" file?
Sorry I'm kind of new with kubernetes

**Comment by travisghansen** [comment]
The example `freenas-iscsi.yaml` is a complete example of a `values.yaml` file to use...in other words just tweak that to your needs and feed it to helm to install. csi has a lot of moving parts so you may need to be a little more patience with it. Just open a issue up over there though and I'll help how I can.

**Comment by UMB8998** [comment]
Thank you
